"""Interfaces for the audio mixer.

The mixer service depends only on these protocols; ``pulsectl`` and GSettings
are the concrete implementations. Tests inject fakes.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from .models import AudioDevice, SinkInput


class AudioBackend(Protocol):
    """Enumerates and controls audio streams."""

    def list_sink_inputs(self) -> list[SinkInput]: ...
    def set_volume(self, index: int, volume: float) -> None: ...
    def set_mute(self, index: int, muted: bool) -> None: ...
    def subscribe(self, callback: Callable[[], None]) -> None: ...


class DeviceBackend(Protocol):
    """Enumerates audio devices and selects the default output/input."""

    def list_sinks(self) -> list[AudioDevice]: ...
    def list_sources(self) -> list[AudioDevice]: ...
    def list_sink_inputs(self) -> list[SinkInput]: ...
    def set_default_sink(self, name: str) -> None: ...
    def set_default_source(self, name: str) -> None: ...
    def move_sink_input(self, input_index: int, sink_index: int) -> None: ...


class VolumeStore(Protocol):
    """Persists per-application volumes."""

    def get_app_volumes(self) -> dict[str, float]: ...
    def set_app_volume(self, app_id: str, volume: float) -> None: ...
